import type { Metadata } from "next";
import "./globals.css";
import Providers from "./Providers";
import Header from "@/components/header/Header";


export const metadata: Metadata = {
  title: "SkyCast",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Providers>
          <Header />
        {children}
        </Providers>
      </body>
    </html>
  );
}
